import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body
  className={`${geistSans.variable} ${geistMono.variable} antialiased 
  bg-gradient-to-br from-black via-[#0f172a] to-blue-900 text-white min-h-screen`}
>
        <Header/>
        <main className="bg-black min-h-screen container">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
